-- ====================================================================
-- HEDTRO JEANS OFFICIAL - SUPABASE DATABASE SCHEMA SETUP
-- Buka Supabase Dashboard -> SQL Editor -> Paste & Run Script Ini
-- ====================================================================

-- 1. TABEL USERS (Master Data Member & Jaringan MLM)
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username TEXT UNIQUE NOT NULL,
  fullname TEXT,
  email TEXT,
  phone TEXT,
  password TEXT DEFAULT 'user123',
  is_active BOOLEAN DEFAULT false,
  role TEXT DEFAULT 'user',
  upline_id BIGINT,
  position TEXT DEFAULT 'L',
  sponsor_id BIGINT,
  sponsor_username TEXT,
  balance NUMERIC DEFAULT 0,
  sponsor_bonus NUMERIC DEFAULT 0,
  pairing_bonus NUMERIC DEFAULT 0,
  level_bonus NUMERIC DEFAULT 0,
  ro_bonus NUMERIC DEFAULT 0,
  left_count INTEGER DEFAULT 0,
  right_count INTEGER DEFAULT 0,
  left_sales NUMERIC DEFAULT 0,
  right_sales NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TABEL PRODUCTS (Katalog Celana Jeans)
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC DEFAULT 0,
  member_price NUMERIC DEFAULT 0,
  stock INTEGER DEFAULT 0,
  image TEXT
);

-- 3. TABEL DEPOSIT_REQUESTS (Permintaan Topup & Pembayaran)
CREATE TABLE IF NOT EXISTS public.deposit_requests (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT,
  username TEXT,
  amount NUMERIC DEFAULT 0,
  unique_code INTEGER DEFAULT 0,
  method TEXT,
  status TEXT DEFAULT 'pending',
  payment_code TEXT,
  midtrans_order_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TABEL WD_REQUESTS (Penarikan Bonus / Payout)
CREATE TABLE IF NOT EXISTS public.wd_requests (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT,
  username TEXT,
  amount NUMERIC DEFAULT 0,
  bank_name TEXT,
  account_number TEXT,
  account_holder TEXT,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. TABEL TRANSACTIONS (Riwayat Mutasi Saldo & Bonus)
CREATE TABLE IF NOT EXISTS public.transactions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT,
  username TEXT,
  type TEXT,
  amount NUMERIC DEFAULT 0,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. TABEL NOTIFICATIONS (Notifikasi System & Member)
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT,
  title TEXT,
  message TEXT,
  type TEXT DEFAULT 'info',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. TABEL ORDERS (Pesanan Paket Perdana & Produk)
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT,
  username TEXT,
  fullname TEXT,
  phone TEXT,
  address TEXT,
  product_name TEXT,
  selected_size TEXT,
  selected_color TEXT,
  amount NUMERIC DEFAULT 0,
  payment_method TEXT,
  status TEXT DEFAULT 'MENUNGGU_PEMBAYARAN',
  courier TEXT,
  tracking_number TEXT,
  notes TEXT,
  steps JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. TABEL SYSTEM_SETTINGS (Pengaturan Bonus & Perusahaan)
CREATE TABLE IF NOT EXISTS public.system_settings (
  id BIGINT PRIMARY KEY,
  data JSONB
);

-- ====================================================================
-- MATIKAN RLS (Row Level Security) SUPAYA API ANON/PUBLIC BISA AKSES
-- ====================================================================
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.deposit_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.wd_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_settings DISABLE ROW LEVEL SECURITY;

-- SEED DATA AWAL ADMIN JIKA KOSONG
INSERT INTO public.users (id, username, fullname, email, phone, password, is_active, role, balance)
VALUES (1, 'admin', 'Administrator Hedtro Jeans', 'admin@hedtrojeans.com', '081234567890', 'admin123', true, 'admin', 5000000)
ON CONFLICT (id) DO NOTHING;
