-- SQL Schema untuk Supabase (Jalankan di Supabase Dashboard -> SQL Editor)

-- 1. Table Users
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  fullname VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  phone VARCHAR(30) NOT NULL,
  is_active BOOLEAN DEFAULT false,
  upline_id BIGINT REFERENCES public.users(id),
  position VARCHAR(5),
  sponsor_id BIGINT REFERENCES public.users(id),
  balance NUMERIC(15,2) DEFAULT 0,
  sponsor_bonus NUMERIC(15,2) DEFAULT 0,
  pairing_bonus NUMERIC(15,2) DEFAULT 0,
  level_bonus NUMERIC(15,2) DEFAULT 0,
  ro_bonus NUMERIC(15,2) DEFAULT 0,
  left_count INT DEFAULT 0,
  right_count INT DEFAULT 0,
  left_sales INT DEFAULT 0,
  right_sales INT DEFAULT 0,
  role VARCHAR(20) DEFAULT 'user',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Table Products
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  price NUMERIC(15,2) NOT NULL,
  member_price NUMERIC(15,2) NOT NULL,
  stock INT DEFAULT 0,
  image TEXT
);

-- 3. Table Transactions
CREATE TABLE IF NOT EXISTS public.transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id),
  username VARCHAR(50) NOT NULL,
  type VARCHAR(50) NOT NULL,
  amount NUMERIC(15,2) NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Table Deposit Requests
CREATE TABLE IF NOT EXISTS public.deposit_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id),
  username VARCHAR(50) NOT NULL,
  amount NUMERIC(15,2) NOT NULL,
  method VARCHAR(20) NOT NULL,
  status VARCHAR(20) DEFAULT 'pending',
  payment_code VARCHAR(100),
  midtrans_order_id VARCHAR(100),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Table WD Requests
CREATE TABLE IF NOT EXISTS public.wd_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id),
  username VARCHAR(50) NOT NULL,
  amount NUMERIC(15,2) NOT NULL,
  bank_name VARCHAR(50) NOT NULL,
  account_number VARCHAR(50) NOT NULL,
  account_holder VARCHAR(100) NOT NULL,
  status VARCHAR(20) DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed Default Admin User
INSERT INTO public.users (username, fullname, email, phone, is_active, balance, role)
VALUES ('admin', 'Administrator Zalora Denim', 'admin@zaloradenim.com', '081234567890', true, 5000000, 'admin')
ON CONFLICT (username) DO NOTHING;
